[build-system]
requires = ["flit_core>=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "S5"
version = "1.0.b2"
authors = [{name = "Owen Foo", email = "owentmfoo@gmail.com"}]
description = "SolarSim Strategy Support Software"
readme = "README.md"
requires-python=">=3.6"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Operating System :: OS Independent",
]


dependencies = [
    "pandas",
    "matplotlib"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

